### ISSUE TITLE
Make a video

### ISSUE THREAD

**Issue by gotoplanb** [c4gnv/c4gnv.github.io#18]
## Specs
- What is CfA?
- What is mission of C4GNV?
- Community and government endorsements of need for C4GNV
- B-roll of people having fun and being all civic and stuff
## Tasks
- [x] Talk to UF The Agency about donating a video
- [ ] Get video from our kickoff/NDCH
- [ ]  Interviews with Lauren Poe
- [ ]  Interview with Susan Davenport
- [ ]  Make a video
- [ ]  Upload video to Drive and link from this ticket

**Comment by gotoplanb** [comment]
I contact Andy Hopson at The Agency. Awaiting response.
