### ISSUE TITLE
"What is CfA" presentation deck

### ISSUE THREAD

**Issue by gotoplanb** [c4gnv/c4gnv.github.io#3]
## Specs

* 10-minute maximum
* What is CfA?

## Tasks

* [x] Create draft deck
* [x] Proofread the deck and ask for any revisions from core team
* [x] Revise deck
* [x] Upload final deck to Drive and link from this ticket

**Comment by gotoplanb** [comment]
@ambercabrera Assigned to you, with some initial specs and tasks, but really just please do what feels right to you.

**Comment by ambercabrera** [comment]
I thought that combining the "what is CfA" and Intro to Code for Gainesville presentations flowed better. Here is the slide deck and I will add this to the other issue ticket as well. [bit.do/NDoCH-deck](url)

**Comment by gotoplanb** [comment]
Revised and done.

**Comment by samanthawolfe** [comment]
@gotoplanb For slide about the brigade not just being for coders:

“We are open to anyone and everyone who cares about making Wichita a better place using creative solutions.” – Open Wichita

Brigades need leaders and members with all types of skillsets. Some ways non-technical folks participate include storytelling, community organizing, advising on projects as subject matter experts, planning events, writing copy, and more.” – Code for Durham

**Comment by gotoplanb** [comment]
Done. Sorry @samanthawolfe for not making that last slide 😞 I'll add these wonderful quotes to our primary readme.

**Comment by samanthawolfe** [comment]
No worries! I should've been more proactive and added myself... You guys
have had enough on your plate :) Awesome job!!
