### ISSUE TITLE
"Gainesville Business Portal" project kickoff deck

### ISSUE THREAD

**Issue by gotoplanb** [c4gnv/c4gnv.github.io#4]
## Specs

* 10-minute maximum
* What is the problem?
* What is the recommended solution?
* What work has been done so far?
* How can you help?

## Tasks

* [x] Give Carrie specs
* [ ] Get draft deck
* [ ] Proofread the deck and ask for any revisions
* [ ] Get final deck
* [ ] Upload final deck to Drive and link from this ticket

**Comment by gotoplanb** [comment]
@ambercabrera I'm assigning this to you to coordinate with Carrie. Holler if you have another suggestion.

**Comment by ambercabrera** [comment]
Carrie thought it would be ok for me and Dave to jointly present this project.

**Comment by gotoplanb** [comment]
We'll just talk about ideas versus showing a deck.
